name: Release Workflow

on:
  release:
    types: [created]

env:
  IMAGE_NAME: dl-s3imgs-redir

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login gh container registry
        run: echo ${{ secrets.G_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Build
        run: docker build -t ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF#refs/*/} .
      - name: Push
        run: docker push ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_REF#refs/*/}
      


